name: bioinfo
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.11.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - bcftools=1.22
  - beautifulsoup4=4.14.2
  - bedtools=2.31.1
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fqdn=1.5.1
  - gsl=2.7
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - htslib=1.22.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - k8=1.2
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lark=1.3.0
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopenssl-static=3.5.4
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - mariadb-connector-c=3.4.7
  - matplotlib-inline=0.1.7
  - minimap2=2.30
  - mistune=3.1.4
  - mysql-connector-c=6.1.11
  - nb_conda_kernels=2.5.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.4.7
  - notebook-shim=0.2.4
  - openssl=3.5.4
  - overrides=7.7.0
  - packaging=25.0
  - paf2chain=0.1.1
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pathlib=1.0.1
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - popt=1.16
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pysam=0.23.3
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.27.1
  - rsync=3.4.1
  - samtools=1.22.1
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - sysroot_linux-64=2.34
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - ucsc-liftover=482
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xxhash=0.8.3
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - click==8.3.0
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - cyvcf2==0.31.4
      - fonttools==4.60.1
      - hdbscan==0.8.40
      - htmlmin==0.1.12
      - humanfriendly==10.0
      - imagehash==4.3.2
      - iprogress==0.4
      - ipywidgets==8.1.7
      - joblib==1.5.2
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - missingno==0.5.2
      - multimethod==2.0
      - natsort==8.4.0
      - ncls==0.0.70
      - networkx==3.5
      - numpy==2.3.3
      - pandas==2.3.3
      - pandas-profiling==3.2.0
      - phik==0.12.5
      - pillow==11.3.0
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pyparsing==3.2.5
      - pyranges==0.1.4
      - pywavelets==1.9.0
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - sorted-nearest==0.0.41
      - tabulate==0.9.0
      - tangled-up-in-unicode==0.2.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - visions==0.7.4
      - widgetsnbextension==4.0.14
